USE pet_store;

SELECT * FROM people;

INSERT INTO people VALUES ('Rakesh', CURDATE(), CURTIME(), NOW());

SELECT * FROM people;

SELECT DATEDIFF(CURDATE(), birthdt) FROM people;

SELECT DATE_ADD(CURDATE(), INTERVAL 1 DAY);

SELECT DATE_ADD(CURDATE(), INTERVAL 1 YEAR);